<?php


/**
 * Skeleton subclass for representing a row from the 'potrero' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/15/15 00:21:46
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Potrero extends BasePotrero {

} // Potrero
