<?php


/**
 * Skeleton subclass for representing a row from the 'subservicio_archivo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/17/15 23:02:18
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SubservicioArchivo extends BaseSubservicioArchivo {

} // SubservicioArchivo
