<?php


/**
 * This class defines the structure of the 'servicio' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/14/15 03:57:46
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ServicioTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ServicioTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('servicio');
		$this->setPhpName('Servicio');
		$this->setClassname('Servicio');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('SER_ID', 'SerId', 'INTEGER', true, 11, null);
		$this->addForeignKey('SER_SER_ID', 'SerSerId', 'INTEGER', 'servicio', 'SER_ID', false, 11, null);
		$this->addColumn('SER_TITULO', 'SerTitulo', 'VARCHAR', false, 255, null);
		$this->addColumn('SER_CONTENIDO', 'SerContenido', 'LONGVARCHAR', false, null, null);
		$this->addColumn('SER_IMAGEN', 'SerImagen', 'VARCHAR', false, 255, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('ServicioRelatedBySerSerId', 'Servicio', RelationMap::MANY_TO_ONE, array('ser_ser_id' => 'ser_id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('ServicioRelatedBySerSerId', 'Servicio', RelationMap::ONE_TO_MANY, array('ser_id' => 'ser_ser_id', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // ServicioTableMap
