<?php

/**
 * Base class that represents a row from the 'proyecto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/15/15 00:21:46
 *
 * @package    lib.model.om
 */
abstract class BaseProyecto extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ProyectoPeer
	 */
	protected static $peer;

	/**
	 * The value for the pro_id field.
	 * @var        int
	 */
	protected $pro_id;

	/**
	 * The value for the pot_id field.
	 * @var        int
	 */
	protected $pot_id;

	/**
	 * The value for the tpr_id field.
	 * @var        int
	 */
	protected $tpr_id;

	/**
	 * The value for the pro_nombre field.
	 * @var        string
	 */
	protected $pro_nombre;

	/**
	 * The value for the pro_fecha field.
	 * @var        string
	 */
	protected $pro_fecha;

	/**
	 * The value for the pro_descripcion field.
	 * @var        string
	 */
	protected $pro_descripcion;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * @var        Potrero
	 */
	protected $aPotrero;

	/**
	 * @var        TipoProyecto
	 */
	protected $aTipoProyecto;

	/**
	 * @var        array ProyectoArchivo[] Collection to store aggregation of ProyectoArchivo objects.
	 */
	protected $collProyectoArchivos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collProyectoArchivos.
	 */
	private $lastProyectoArchivoCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ProyectoPeer';

	/**
	 * Get the [pro_id] column value.
	 * 
	 * @return     int
	 */
	public function getProId()
	{
		return $this->pro_id;
	}

	/**
	 * Get the [pot_id] column value.
	 * 
	 * @return     int
	 */
	public function getPotId()
	{
		return $this->pot_id;
	}

	/**
	 * Get the [tpr_id] column value.
	 * 
	 * @return     int
	 */
	public function getTprId()
	{
		return $this->tpr_id;
	}

	/**
	 * Get the [pro_nombre] column value.
	 * 
	 * @return     string
	 */
	public function getProNombre()
	{
		return $this->pro_nombre;
	}

	/**
	 * Get the [optionally formatted] temporal [pro_fecha] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getProFecha($format = 'Y-m-d H:i:s')
	{
		if ($this->pro_fecha === null) {
			return null;
		}


		if ($this->pro_fecha === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->pro_fecha);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->pro_fecha, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [pro_descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getProDescripcion()
	{
		return $this->pro_descripcion;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [pro_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Proyecto The current object (for fluent API support)
	 */
	public function setProId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pro_id !== $v) {
			$this->pro_id = $v;
			$this->modifiedColumns[] = ProyectoPeer::PRO_ID;
		}

		return $this;
	} // setProId()

	/**
	 * Set the value of [pot_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Proyecto The current object (for fluent API support)
	 */
	public function setPotId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pot_id !== $v) {
			$this->pot_id = $v;
			$this->modifiedColumns[] = ProyectoPeer::POT_ID;
		}

		if ($this->aPotrero !== null && $this->aPotrero->getPotId() !== $v) {
			$this->aPotrero = null;
		}

		return $this;
	} // setPotId()

	/**
	 * Set the value of [tpr_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Proyecto The current object (for fluent API support)
	 */
	public function setTprId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tpr_id !== $v) {
			$this->tpr_id = $v;
			$this->modifiedColumns[] = ProyectoPeer::TPR_ID;
		}

		if ($this->aTipoProyecto !== null && $this->aTipoProyecto->getTprId() !== $v) {
			$this->aTipoProyecto = null;
		}

		return $this;
	} // setTprId()

	/**
	 * Set the value of [pro_nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     Proyecto The current object (for fluent API support)
	 */
	public function setProNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pro_nombre !== $v) {
			$this->pro_nombre = $v;
			$this->modifiedColumns[] = ProyectoPeer::PRO_NOMBRE;
		}

		return $this;
	} // setProNombre()

	/**
	 * Sets the value of [pro_fecha] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Proyecto The current object (for fluent API support)
	 */
	public function setProFecha($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->pro_fecha !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->pro_fecha !== null && $tmpDt = new DateTime($this->pro_fecha)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->pro_fecha = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ProyectoPeer::PRO_FECHA;
			}
		} // if either are not null

		return $this;
	} // setProFecha()

	/**
	 * Set the value of [pro_descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     Proyecto The current object (for fluent API support)
	 */
	public function setProDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pro_descripcion !== $v) {
			$this->pro_descripcion = $v;
			$this->modifiedColumns[] = ProyectoPeer::PRO_DESCRIPCION;
		}

		return $this;
	} // setProDescripcion()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Proyecto The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ProyectoPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->pro_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->pot_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->tpr_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->pro_nombre = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->pro_fecha = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->pro_descripcion = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->created_at = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = ProyectoPeer::NUM_COLUMNS - ProyectoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Proyecto object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPotrero !== null && $this->pot_id !== $this->aPotrero->getPotId()) {
			$this->aPotrero = null;
		}
		if ($this->aTipoProyecto !== null && $this->tpr_id !== $this->aTipoProyecto->getTprId()) {
			$this->aTipoProyecto = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProyectoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ProyectoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPotrero = null;
			$this->aTipoProyecto = null;
			$this->collProyectoArchivos = null;
			$this->lastProyectoArchivoCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProyectoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseProyecto:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ProyectoPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseProyecto:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProyectoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseProyecto:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			
			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(ProyectoPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseProyecto:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ProyectoPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPotrero !== null) {
				if ($this->aPotrero->isModified() || $this->aPotrero->isNew()) {
					$affectedRows += $this->aPotrero->save($con);
				}
				$this->setPotrero($this->aPotrero);
			}

			if ($this->aTipoProyecto !== null) {
				if ($this->aTipoProyecto->isModified() || $this->aTipoProyecto->isNew()) {
					$affectedRows += $this->aTipoProyecto->save($con);
				}
				$this->setTipoProyecto($this->aTipoProyecto);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ProyectoPeer::PRO_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ProyectoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setProId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ProyectoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collProyectoArchivos !== null) {
				foreach ($this->collProyectoArchivos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPotrero !== null) {
				if (!$this->aPotrero->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPotrero->getValidationFailures());
				}
			}

			if ($this->aTipoProyecto !== null) {
				if (!$this->aTipoProyecto->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTipoProyecto->getValidationFailures());
				}
			}


			if (($retval = ProyectoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collProyectoArchivos !== null) {
					foreach ($this->collProyectoArchivos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ProyectoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getProId();
				break;
			case 1:
				return $this->getPotId();
				break;
			case 2:
				return $this->getTprId();
				break;
			case 3:
				return $this->getProNombre();
				break;
			case 4:
				return $this->getProFecha();
				break;
			case 5:
				return $this->getProDescripcion();
				break;
			case 6:
				return $this->getCreatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ProyectoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getProId(),
			$keys[1] => $this->getPotId(),
			$keys[2] => $this->getTprId(),
			$keys[3] => $this->getProNombre(),
			$keys[4] => $this->getProFecha(),
			$keys[5] => $this->getProDescripcion(),
			$keys[6] => $this->getCreatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ProyectoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setProId($value);
				break;
			case 1:
				$this->setPotId($value);
				break;
			case 2:
				$this->setTprId($value);
				break;
			case 3:
				$this->setProNombre($value);
				break;
			case 4:
				$this->setProFecha($value);
				break;
			case 5:
				$this->setProDescripcion($value);
				break;
			case 6:
				$this->setCreatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ProyectoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setProId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPotId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTprId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setProNombre($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setProFecha($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setProDescripcion($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCreatedAt($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ProyectoPeer::DATABASE_NAME);

		if ($this->isColumnModified(ProyectoPeer::PRO_ID)) $criteria->add(ProyectoPeer::PRO_ID, $this->pro_id);
		if ($this->isColumnModified(ProyectoPeer::POT_ID)) $criteria->add(ProyectoPeer::POT_ID, $this->pot_id);
		if ($this->isColumnModified(ProyectoPeer::TPR_ID)) $criteria->add(ProyectoPeer::TPR_ID, $this->tpr_id);
		if ($this->isColumnModified(ProyectoPeer::PRO_NOMBRE)) $criteria->add(ProyectoPeer::PRO_NOMBRE, $this->pro_nombre);
		if ($this->isColumnModified(ProyectoPeer::PRO_FECHA)) $criteria->add(ProyectoPeer::PRO_FECHA, $this->pro_fecha);
		if ($this->isColumnModified(ProyectoPeer::PRO_DESCRIPCION)) $criteria->add(ProyectoPeer::PRO_DESCRIPCION, $this->pro_descripcion);
		if ($this->isColumnModified(ProyectoPeer::CREATED_AT)) $criteria->add(ProyectoPeer::CREATED_AT, $this->created_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ProyectoPeer::DATABASE_NAME);

		$criteria->add(ProyectoPeer::PRO_ID, $this->pro_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getProId();
	}

	/**
	 * Generic method to set the primary key (pro_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setProId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Proyecto (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPotId($this->pot_id);

		$copyObj->setTprId($this->tpr_id);

		$copyObj->setProNombre($this->pro_nombre);

		$copyObj->setProFecha($this->pro_fecha);

		$copyObj->setProDescripcion($this->pro_descripcion);

		$copyObj->setCreatedAt($this->created_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getProyectoArchivos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addProyectoArchivo($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setProId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Proyecto Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ProyectoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ProyectoPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Potrero object.
	 *
	 * @param      Potrero $v
	 * @return     Proyecto The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPotrero(Potrero $v = null)
	{
		if ($v === null) {
			$this->setPotId(NULL);
		} else {
			$this->setPotId($v->getPotId());
		}

		$this->aPotrero = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Potrero object, it will not be re-added.
		if ($v !== null) {
			$v->addProyecto($this);
		}

		return $this;
	}


	/**
	 * Get the associated Potrero object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Potrero The associated Potrero object.
	 * @throws     PropelException
	 */
	public function getPotrero(PropelPDO $con = null)
	{
		if ($this->aPotrero === null && ($this->pot_id !== null)) {
			$this->aPotrero = PotreroPeer::retrieveByPk($this->pot_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPotrero->addProyectos($this);
			 */
		}
		return $this->aPotrero;
	}

	/**
	 * Declares an association between this object and a TipoProyecto object.
	 *
	 * @param      TipoProyecto $v
	 * @return     Proyecto The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTipoProyecto(TipoProyecto $v = null)
	{
		if ($v === null) {
			$this->setTprId(NULL);
		} else {
			$this->setTprId($v->getTprId());
		}

		$this->aTipoProyecto = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the TipoProyecto object, it will not be re-added.
		if ($v !== null) {
			$v->addProyecto($this);
		}

		return $this;
	}


	/**
	 * Get the associated TipoProyecto object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     TipoProyecto The associated TipoProyecto object.
	 * @throws     PropelException
	 */
	public function getTipoProyecto(PropelPDO $con = null)
	{
		if ($this->aTipoProyecto === null && ($this->tpr_id !== null)) {
			$this->aTipoProyecto = TipoProyectoPeer::retrieveByPk($this->tpr_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTipoProyecto->addProyectos($this);
			 */
		}
		return $this->aTipoProyecto;
	}

	/**
	 * Clears out the collProyectoArchivos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addProyectoArchivos()
	 */
	public function clearProyectoArchivos()
	{
		$this->collProyectoArchivos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collProyectoArchivos collection (array).
	 *
	 * By default this just sets the collProyectoArchivos collection to an empty array (like clearcollProyectoArchivos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initProyectoArchivos()
	{
		$this->collProyectoArchivos = array();
	}

	/**
	 * Gets an array of ProyectoArchivo objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Proyecto has previously been saved, it will retrieve
	 * related ProyectoArchivos from storage. If this Proyecto is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ProyectoArchivo[]
	 * @throws     PropelException
	 */
	public function getProyectoArchivos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProyectoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProyectoArchivos === null) {
			if ($this->isNew()) {
			   $this->collProyectoArchivos = array();
			} else {

				$criteria->add(ProyectoArchivoPeer::PRO_ID, $this->pro_id);

				ProyectoArchivoPeer::addSelectColumns($criteria);
				$this->collProyectoArchivos = ProyectoArchivoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ProyectoArchivoPeer::PRO_ID, $this->pro_id);

				ProyectoArchivoPeer::addSelectColumns($criteria);
				if (!isset($this->lastProyectoArchivoCriteria) || !$this->lastProyectoArchivoCriteria->equals($criteria)) {
					$this->collProyectoArchivos = ProyectoArchivoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastProyectoArchivoCriteria = $criteria;
		return $this->collProyectoArchivos;
	}

	/**
	 * Returns the number of related ProyectoArchivo objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ProyectoArchivo objects.
	 * @throws     PropelException
	 */
	public function countProyectoArchivos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProyectoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collProyectoArchivos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ProyectoArchivoPeer::PRO_ID, $this->pro_id);

				$count = ProyectoArchivoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ProyectoArchivoPeer::PRO_ID, $this->pro_id);

				if (!isset($this->lastProyectoArchivoCriteria) || !$this->lastProyectoArchivoCriteria->equals($criteria)) {
					$count = ProyectoArchivoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collProyectoArchivos);
				}
			} else {
				$count = count($this->collProyectoArchivos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ProyectoArchivo object to this object
	 * through the ProyectoArchivo foreign key attribute.
	 *
	 * @param      ProyectoArchivo $l ProyectoArchivo
	 * @return     void
	 * @throws     PropelException
	 */
	public function addProyectoArchivo(ProyectoArchivo $l)
	{
		if ($this->collProyectoArchivos === null) {
			$this->initProyectoArchivos();
		}
		if (!in_array($l, $this->collProyectoArchivos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collProyectoArchivos, $l);
			$l->setProyecto($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collProyectoArchivos) {
				foreach ((array) $this->collProyectoArchivos as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collProyectoArchivos = null;
			$this->aPotrero = null;
			$this->aTipoProyecto = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseProyecto:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseProyecto::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseProyecto
